// Known-phishing URL lookups (REP-05, "Link is on a known-malicious list").
//
// Sources, both plain text in data/threat-intel/, one URL or hostname per
// line, "#" comments allowed:
//   - openphish.txt       OpenPhish community feed, regenerated by
//                         `npm run update:threat-feed` (gitignored - it's
//                         third-party data that goes stale within hours)
//   - local-blocklist.txt entries the team adds by hand (committed)
//
// Matching rule - the part that keeps this from causing false positives:
// feeds list phishing pages on SHARED hosts too (a Google Form, a GitHub
// Pages site, a Weebly page). Blocking by hostname there would flag every
// page on docs.google.com. So:
//   - on a shared host (trusted domain, user-content host or free-hosting
//     platform), only the listed URL path (or a path under it) matches;
//   - on any other host, the hostname itself matches (the whole domain was
//     registered for phishing);
//   - an official institution domain (mcb.mu ...) never matches at all.
//
// Files are re-read when they change (checked at most every 60s), so a feed
// refresh takes effect without restarting the backend.

import { readdirSync, readFileSync, statSync, existsSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { institutionForHost, normalizeHost } from "../institutions/index.js";
import { extractLinks, isTrustedDomain } from "../domain-matching/index.js";
import { isUserContentHost } from "../domain-matching/trustedDomains.js";
import { makeSignal } from "../signals/registry.js";

// THREAT_INTEL_DIR overrides the folder (tests point it at fixtures).
const DATA_DIR = process.env.THREAT_INTEL_DIR
  ? pathToFileURL(`${process.env.THREAT_INTEL_DIR.replace(/[\\/]+$/, "")}/`)
  : new URL("../../../../data/threat-intel/", import.meta.url);
const RECHECK_MS = 60 * 1000;

// Free-hosting / site-builder platforms: one customer's phishing page says
// nothing about the platform's other customers.
const SHARED_HOST_SUFFIXES = [
  "github.io", "gitlab.io", "pages.dev", "workers.dev", "netlify.app", "vercel.app", "web.app", "firebaseapp.com",
  "herokuapp.com", "glitch.me", "repl.co", "replit.app", "onrender.com", "fly.dev", "azurewebsites.net", "blob.core.windows.net",
  "amazonaws.com", "cloudfront.net", "appspot.com", "weebly.com", "wixsite.com", "wix.com", "square.site", "godaddysites.com",
  "blogspot.com", "wordpress.com", "webflow.io", "framer.app", "carrd.co", "notion.site", "000webhostapp.com", "ngrok.io",
  "ngrok-free.app", "trycloudflare.com", "ipfs.io", "dweb.link", "myshopify.com", "sharepoint.com", "typeform.com", "jotform.com",
];

function isSharedHost(host) {
  return isTrustedDomain(host) || isUserContentHost(host) || SHARED_HOST_SUFFIXES.some((s) => host === s || host.endsWith(`.${s}`));
}

let state = { hosts: new Map(), paths: new Map(), sources: [], loadedAt: 0, signature: "" };

function listFiles() {
  if (!existsSync(DATA_DIR)) return [];
  return readdirSync(DATA_DIR)
    .filter((f) => f.endsWith(".txt"))
    .map((f) => new URL(f, DATA_DIR));
}

function parseEntry(line) {
  const raw = line.split(/\s+#/)[0].trim(); // allow "host   # note"
  if (!raw || raw.startsWith("#")) return null;
  try {
    const u = new URL(/^[a-z][a-z0-9+.-]*:\/\//i.test(raw) ? raw : `http://${raw}`);
    const host = normalizeHost(u.hostname);
    if (!host) return null;
    const path = u.pathname.replace(/\/+$/, "") || "";
    return { host, path };
  } catch {
    return null;
  }
}

function load() {
  const files = listFiles();
  const signature = files.map((f) => `${f.pathname}:${statSync(f).mtimeMs}`).join("|");
  if (signature === state.signature) return;
  const hosts = new Map(); // host -> source
  const paths = new Map(); // host -> [{ path, source }]
  const sources = [];
  for (const file of files) {
    const name = decodeURIComponent(file.pathname.split("/").pop());
    const text = readFileSync(file, "utf8");
    const fetchedAt = /^#\s*fetched:\s*(\S+)/im.exec(text)?.[1] ?? null;
    let count = 0;
    for (const line of text.split(/\r?\n/)) {
      const entry = parseEntry(line);
      if (!entry || institutionForHost(entry.host)) continue;
      count++;
      if (isSharedHost(entry.host)) {
        // A bare shared host with no path can't be used safely - skip it.
        if (!entry.path) continue;
        if (!paths.has(entry.host)) paths.set(entry.host, []);
        paths.get(entry.host).push({ path: entry.path, source: name });
      } else if (!hosts.has(entry.host)) {
        hosts.set(entry.host, name);
      }
    }
    sources.push({ file: name, entries: count, fetchedAt });
  }
  state = { hosts, paths, sources, loadedAt: Date.now(), signature };
}

function ensureFresh() {
  if (Date.now() - state.loadedAt < RECHECK_MS && state.signature) return;
  try {
    load();
  } catch (err) {
    console.error(`[threat-intel] reload failed, keeping previous lists: ${err.message}`);
    state.loadedAt = Date.now();
  }
}

/** Test seam: force a reload now (the 60s throttle otherwise applies). */
export function _reloadThreatIntel() {
  state.signature = "";
  state.loadedAt = 0;
  ensureFresh();
}

/** @returns {{ sources: {file: string, entries: number, fetchedAt: string|null}[] }} */
export function threatIntelStatus() {
  ensureFresh();
  return { sources: state.sources };
}

/**
 * @param {string} url
 * @returns {{ listed: boolean, source?: string, match?: "host"|"path" }}
 */
export function lookupUrl(url) {
  ensureFresh();
  let u;
  try {
    u = new URL(url);
  } catch {
    return { listed: false };
  }
  const host = normalizeHost(u.hostname);
  if (!host || institutionForHost(host)) return { listed: false };
  const hostSource = state.hosts.get(host);
  if (hostSource && !isSharedHost(host)) return { listed: true, source: hostSource, match: "host" };
  const path = u.pathname.replace(/\/+$/, "");
  for (const entry of state.paths.get(host) ?? []) {
    if (path === entry.path || path.startsWith(`${entry.path}/`)) return { listed: true, source: entry.source, match: "path" };
  }
  return { listed: false };
}

function hostOf(url) {
  try {
    return normalizeHost(new URL(/^[a-z][a-z0-9+.-]*:\/\//i.test(url) ? url : `http://${url}`).hostname);
  } catch {
    return null;
  }
}

function listedSignal(url, hit, span) {
  const host = hostOf(url);
  return makeSignal("REP-05", {
    sourceType: "intel",
    evidence: url,
    span,
    description: `This link is on a known-phishing list (${hit.source.replace(/\.txt$/, "")}).`,
    metadata: { host, list: hit.source, match: hit.match },
    extra: { domain: host },
  });
}

/** REP-05 for one URL (the page being visited), or [] */
export function checkUrlAgainstThreatIntel(url) {
  const hit = lookupUrl(url);
  return hit.listed ? [listedSignal(url, hit, null)] : [];
}

/** REP-05 for every link in a message that is on a list. */
export function checkThreatIntel(text) {
  const out = [];
  const seen = new Set();
  for (const link of extractLinks(text)) {
    const full = link.hasScheme ? link.url : `http://${link.url}`;
    const hit = lookupUrl(full);
    if (!hit.listed) continue;
    const key = `${link.host}${hit.match === "path" ? link.path : ""}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(listedSignal(link.url, hit, link.span));
  }
  return out;
}
